/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface HalalCertificateRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "authorities"
      | "getCertificateById"
      | "getCertificateByProductId"
      | "getTraceabilityById"
      | "getTraceabilityIdsByProductId"
      | "recordCertificateDecision"
      | "recordTraceability"
      | "setAuthority"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuthorityUpdated"
      | "CertificateDecisionRecorded"
      | "TraceabilityRecorded"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "authorities",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCertificateById",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getCertificateByProductId",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getTraceabilityById",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getTraceabilityIdsByProductId",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "recordCertificateDecision",
    values: [
      string,
      string,
      string,
      string,
      string,
      string,
      BigNumberish,
      BigNumberish,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "recordTraceability",
    values: [string, string, string, string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthority",
    values: [AddressLike, boolean]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "authorities",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCertificateById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCertificateByProductId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTraceabilityById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTraceabilityIdsByProductId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordCertificateDecision",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordTraceability",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAuthority",
    data: BytesLike
  ): Result;
}

export namespace AuthorityUpdatedEvent {
  export type InputTuple = [authorityAddress: AddressLike, allowed: boolean];
  export type OutputTuple = [authorityAddress: string, allowed: boolean];
  export interface OutputObject {
    authorityAddress: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CertificateDecisionRecordedEvent {
  export type InputTuple = [
    certificateId: string,
    productID: string,
    status: BigNumberish,
    certificateHash: string,
    decisionTimestamp: BigNumberish
  ];
  export type OutputTuple = [
    certificateId: string,
    productID: string,
    status: bigint,
    certificateHash: string,
    decisionTimestamp: bigint
  ];
  export interface OutputObject {
    certificateId: string;
    productID: string;
    status: bigint;
    certificateHash: string;
    decisionTimestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TraceabilityRecordedEvent {
  export type InputTuple = [
    traceId: string,
    productID: string,
    recordHash: string,
    eventTimestamp: BigNumberish,
    anchoredAt: BigNumberish
  ];
  export type OutputTuple = [
    traceId: string,
    productID: string,
    recordHash: string,
    eventTimestamp: bigint,
    anchoredAt: bigint
  ];
  export interface OutputObject {
    traceId: string;
    productID: string;
    recordHash: string;
    eventTimestamp: bigint;
    anchoredAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HalalCertificateRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): HalalCertificateRegistry;
  waitForDeployment(): Promise<this>;

  interface: HalalCertificateRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  authorities: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getCertificateById: TypedContractMethod<
    [certificateId: string],
    [
      [
        string,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        bigint
      ] & {
        returnedCertificateId: string;
        batchID: string;
        productID: string;
        productName: string;
        authority: string;
        certificateHash: string;
        issueDate: bigint;
        expiryDate: bigint;
        halalStatus: string;
        decisionTimestamp: bigint;
      }
    ],
    "view"
  >;

  getCertificateByProductId: TypedContractMethod<
    [productID: string],
    [
      [
        string,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        bigint
      ] & {
        returnedCertificateId: string;
        batchID: string;
        returnedProductID: string;
        productName: string;
        authority: string;
        certificateHash: string;
        issueDate: bigint;
        expiryDate: bigint;
        halalStatus: string;
        decisionTimestamp: bigint;
      }
    ],
    "view"
  >;

  getTraceabilityById: TypedContractMethod<
    [traceId: string],
    [
      [string, string, string, string, string, string, bigint, bigint] & {
        returnedTraceId: string;
        productID: string;
        batchID: string;
        stage: string;
        actorName: string;
        recordHash: string;
        eventTimestamp: bigint;
        anchoredAt: bigint;
      }
    ],
    "view"
  >;

  getTraceabilityIdsByProductId: TypedContractMethod<
    [productID: string],
    [string[]],
    "view"
  >;

  recordCertificateDecision: TypedContractMethod<
    [
      certificateId: string,
      batchID: string,
      productID: string,
      productName: string,
      authority: string,
      certificateHash: string,
      issueDate: BigNumberish,
      expiryDate: BigNumberish,
      approved: boolean
    ],
    [void],
    "nonpayable"
  >;

  recordTraceability: TypedContractMethod<
    [
      traceId: string,
      productID: string,
      batchID: string,
      stage: string,
      actorName: string,
      recordHash: string,
      eventTimestamp: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  setAuthority: TypedContractMethod<
    [account: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "authorities"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getCertificateById"
  ): TypedContractMethod<
    [certificateId: string],
    [
      [
        string,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        bigint
      ] & {
        returnedCertificateId: string;
        batchID: string;
        productID: string;
        productName: string;
        authority: string;
        certificateHash: string;
        issueDate: bigint;
        expiryDate: bigint;
        halalStatus: string;
        decisionTimestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCertificateByProductId"
  ): TypedContractMethod<
    [productID: string],
    [
      [
        string,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        bigint
      ] & {
        returnedCertificateId: string;
        batchID: string;
        returnedProductID: string;
        productName: string;
        authority: string;
        certificateHash: string;
        issueDate: bigint;
        expiryDate: bigint;
        halalStatus: string;
        decisionTimestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTraceabilityById"
  ): TypedContractMethod<
    [traceId: string],
    [
      [string, string, string, string, string, string, bigint, bigint] & {
        returnedTraceId: string;
        productID: string;
        batchID: string;
        stage: string;
        actorName: string;
        recordHash: string;
        eventTimestamp: bigint;
        anchoredAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTraceabilityIdsByProductId"
  ): TypedContractMethod<[productID: string], [string[]], "view">;
  getFunction(
    nameOrSignature: "recordCertificateDecision"
  ): TypedContractMethod<
    [
      certificateId: string,
      batchID: string,
      productID: string,
      productName: string,
      authority: string,
      certificateHash: string,
      issueDate: BigNumberish,
      expiryDate: BigNumberish,
      approved: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordTraceability"
  ): TypedContractMethod<
    [
      traceId: string,
      productID: string,
      batchID: string,
      stage: string,
      actorName: string,
      recordHash: string,
      eventTimestamp: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAuthority"
  ): TypedContractMethod<
    [account: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AuthorityUpdated"
  ): TypedContractEvent<
    AuthorityUpdatedEvent.InputTuple,
    AuthorityUpdatedEvent.OutputTuple,
    AuthorityUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "CertificateDecisionRecorded"
  ): TypedContractEvent<
    CertificateDecisionRecordedEvent.InputTuple,
    CertificateDecisionRecordedEvent.OutputTuple,
    CertificateDecisionRecordedEvent.OutputObject
  >;
  getEvent(
    key: "TraceabilityRecorded"
  ): TypedContractEvent<
    TraceabilityRecordedEvent.InputTuple,
    TraceabilityRecordedEvent.OutputTuple,
    TraceabilityRecordedEvent.OutputObject
  >;

  filters: {
    "AuthorityUpdated(address,bool)": TypedContractEvent<
      AuthorityUpdatedEvent.InputTuple,
      AuthorityUpdatedEvent.OutputTuple,
      AuthorityUpdatedEvent.OutputObject
    >;
    AuthorityUpdated: TypedContractEvent<
      AuthorityUpdatedEvent.InputTuple,
      AuthorityUpdatedEvent.OutputTuple,
      AuthorityUpdatedEvent.OutputObject
    >;

    "CertificateDecisionRecorded(string,string,uint8,string,uint256)": TypedContractEvent<
      CertificateDecisionRecordedEvent.InputTuple,
      CertificateDecisionRecordedEvent.OutputTuple,
      CertificateDecisionRecordedEvent.OutputObject
    >;
    CertificateDecisionRecorded: TypedContractEvent<
      CertificateDecisionRecordedEvent.InputTuple,
      CertificateDecisionRecordedEvent.OutputTuple,
      CertificateDecisionRecordedEvent.OutputObject
    >;

    "TraceabilityRecorded(string,string,string,uint256,uint256)": TypedContractEvent<
      TraceabilityRecordedEvent.InputTuple,
      TraceabilityRecordedEvent.OutputTuple,
      TraceabilityRecordedEvent.OutputObject
    >;
    TraceabilityRecorded: TypedContractEvent<
      TraceabilityRecordedEvent.InputTuple,
      TraceabilityRecordedEvent.OutputTuple,
      TraceabilityRecordedEvent.OutputObject
    >;
  };
}
