/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { HalalCertificateRegistry } from "./HalalCertificateRegistry";
export * as factories from "./factories";
export { HalalCertificateRegistry__factory } from "./factories/HalalCertificateRegistry__factory";
